project:
  type: book
  output-dir: docs

book:
  title: "CE 307 - Projeto de Extensão"
  # author: "Raymundo"
  # favicon: https://ufpr.br/wp-content/uploads/2015/11/ufpr_25.jpg
  # description: Material da disciplina CE307 - PROJETO DE ANÁLISE DE DADOS do curso de Estatística da Universidade Federal do Paraná (UFPR).
  keyword: statistics, R, quarto, data science, estatistica, ciencia de dados
  # url: https://github.com/raymz1990/CE307-Projeto-Extensao

  repo-subdir: book
  repo-branch: main
  reader-mode: true
  # repo-actions: [edit, issue]

  search: true
  downloads: [pdf, docx]
  # page-navigation: true
  # image: https://ufpr.br/wp-content/uploads/2015/11/ufpr_25.jpg
  
  sidebar: 
    background: "#F5F5F5"
    logo: logo.png
    # pinned: true
    # align: center

  chapters:
    - index.qmd

    - part: 00_presentation.qmd
      chapters:
        - 01_visualizacao-dados.qmd
        - 02_intro-ggplot.qmd
        - 03_graphics.qmd
        - 04_exercises.qmd
        - 05_quizz.qmd

  page-footer: 
    left: |
      Estatística UFPR 2024
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  

format:
  html:
    html:
    theme:
      light: lumen
      dark: slate
    # toc: true # barra lateral esquerda com conteudo
    toc-title: "Nesta página"
    # toc-location: left
    code-fold: false
    code-summary: "R"
    code-overflow: wrap
    code-link: true
    code-tools: false
    code-line-numbers: false
    # fontcolor: '#C25E8C'
    # linkcolor: 'red'
    fontsize: 1.1em
    css: styles.css
    highlight-style: atom-one

execute:
  freeze: auto

# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo
