# Apresentação {.unnumbered}

<br>Estatística e Ciência de Dados - UFPR

---

## Estrutura de Aula: Curso de R para Alunos de Ensino Médio (14-16 anos)

## Objetivos

Introduzir os alunos ao uso da linguagem de programação R para análise de dados, com foco em desenvolver habilidades básicas em programação, análise de dados e visualização, aplicando conceitos matemáticos e estatísticos de maneira prática e acessível.

## Ementa

Relações entre universidade e sociedade; Fundamentos e metodologias de extensão; Concepções e tendências da extensão universitária; Avaliação e planejamento na extensão. Aplicação de técnicas de visualização de dados e análises estatísticas básicas, sob orientação de um professor da área.


**Local**: .
<br>**Horário**: sexta-feira, 6 de dezembro 2024, 15:30 - 17:00h.

## Referências bibliográficas 

1. SOUSA, A. – **A História da Extensão Universitária**, Editora Alinea, 2010. 
2. TAVARES, C.; FREITAS, K. - **Extensão Universitária: O Patinho Feio da Academia?**, 1° edição. Paco Editorial, 2016.
3. FÓRUM DE PRÓ-REITORES DE EXTENSÃO DAS UNIVERSIDADES PÚBLICAS BRASILEIRAS. **Plano Nacional de Extensão Universitária**. Ilhéus; Editus, 2001.
4. GONÇALVES, H. - **Manual de Projetos de Extensão Universitária**, Editora A.
5. MORETTIN, P. A.; SINGER, J. M. **Estatística e Ciência de Dados**. LTC, 2022.
6. CAIRO, A. **The Functional Art: An introduction to information graphics and visualization**. New Riders, 2012.


## Conteúdo Programático

* [**Introdução à Visualização de Dados**](@sec-data-visualization)
  * [O Pacote ggplot2](@sec-intro-ggplot2)
  * [Construção de gráficos com o ggplot2]()
  * [Exercícios]()
  * Quizz

---

* [Outros exemplos de gráficos no R]()


